import React,{useEffect,useState} from "react";
import {SafeAreaView,View,Text,StyleSheet,ScrollView,Pressable,ActivityIndicator} from "react-native";
const API="http://localhost:5000/api";
export default function App(){
 const [projects,setProjects]=useState([]); const [loading,setLoading]=useState(true);
 useEffect(()=>{fetch(API+"/projects").then(r=>r.json()).then(setProjects).catch(()=>{}).finally(()=>setLoading(false))},[]);
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.container}>
  <View style={s.header}><View><Text style={s.kicker}>CLIENT APP</Text><Text style={s.title}>Good morning, Rawan</Text></View><View style={s.avatar}><Text style={s.avatarText}>RM</Text></View></View>
  <View style={s.hero}><Text style={s.heroK}>DATA • INSIGHTS • GROWTH</Text><Text style={s.heroTitle}>Turn Your Data Into Better Decisions.</Text><Text style={s.heroText}>Track projects, meetings and insights from your phone.</Text><Pressable style={s.button}><Text style={s.buttonText}>Start a Project</Text></Pressable></View>
  <Text style={s.section}>Overview</Text><View style={s.stats}>{[["Projects","12"],["Progress","06"],["Done","04"],["Pending","02"]].map(x=><View style={s.card} key={x[0]}><Text style={s.muted}>{x[0]}</Text><Text style={s.value}>{x[1]}</Text></View>)}</View>
  <View style={s.sectionRow}><Text style={s.section}>Recent Projects</Text><Text style={s.link}>View all</Text></View>
  {loading?<ActivityIndicator color="#6c4ce8"/>:projects.map(p=><View style={s.project} key={p.id}><View style={s.projectIcon}><Text style={s.projectIconText}>{(p.domain||"A")[0]}</Text></View><View style={{flex:1}}><Text style={s.projectName}>{p.name}</Text><Text style={s.muted}>{p.domain} · {p.status}</Text><View style={s.progress}><View style={[s.progressFill,{width:`${p.progress||0}%`}]}/></View></View><Text style={s.percent}>{p.progress||0}%</Text></View>)}
  <Text style={s.section}>Upcoming Meeting</Text><View style={s.meeting}><Text style={s.meetingTitle}>Requirements Interview</Text><Text style={s.muted}>Marketing Analysis</Text><Text style={s.meetingTime}>24 Sep · 12:00 PM</Text><Text style={s.muted}>Online Meeting</Text></View>
 </ScrollView></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#f7f7fc"},container:{padding:20,paddingBottom:40},header:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginBottom:22},kicker:{fontSize:9,color:"#aaa7b9",fontWeight:"800",letterSpacing:1.2},title:{fontSize:19,fontWeight:"800",color:"#171725",marginTop:3},avatar:{width:38,height:38,borderRadius:19,backgroundColor:"#6c4ce8",alignItems:"center",justifyContent:"center"},avatarText:{color:"#fff",fontSize:10,fontWeight:"800"},hero:{backgroundColor:"#5d42cf",borderRadius:22,padding:24,marginBottom:20},heroK:{color:"#ddd5ff",fontSize:9,fontWeight:"800",letterSpacing:1.2},heroTitle:{color:"#fff",fontSize:29,fontWeight:"900",lineHeight:32,marginVertical:10},heroText:{color:"#e1dcf3",fontSize:12,lineHeight:18,marginBottom:18},button:{backgroundColor:"#fff",paddingVertical:11,paddingHorizontal:15,borderRadius:10,alignSelf:"flex-start"},buttonText:{color:"#4e31bd",fontWeight:"800",fontSize:11},section:{fontSize:15,fontWeight:"800",color:"#171725",marginTop:8,marginBottom:10},sectionRow:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},link:{color:"#6c4ce8",fontSize:10,fontWeight:"800"},stats:{flexDirection:"row",flexWrap:"wrap",gap:10,marginBottom:15},card:{width:"47%",backgroundColor:"#fff",borderRadius:14,padding:15,borderWidth:1,borderColor:"#ebe9f3"},muted:{color:"#858399",fontSize:9,marginTop:3},value:{fontSize:23,fontWeight:"900",color:"#171725",marginTop:3},project:{backgroundColor:"#fff",borderRadius:15,padding:13,marginBottom:9,flexDirection:"row",gap:10,alignItems:"center",borderWidth:1,borderColor:"#ebe9f3"},projectIcon:{width:38,height:38,borderRadius:11,backgroundColor:"#f1eeff",alignItems:"center",justifyContent:"center"},projectIconText:{color:"#6c4ce8",fontWeight:"900"},projectName:{fontSize:11,fontWeight:"800",color:"#171725"},progress:{height:5,backgroundColor:"#eeeaf5",borderRadius:5,overflow:"hidden",marginTop:8},progressFill:{height:5,backgroundColor:"#6c4ce8"},percent:{fontSize:9,fontWeight:"800",color:"#6c4ce8"},meeting:{backgroundColor:"#fff",borderRadius:16,padding:17,borderWidth:1,borderColor:"#ebe9f3"},meetingTitle:{fontSize:13,fontWeight:"800",color:"#171725"},meetingTime:{fontSize:11,fontWeight:"800",color:"#6c4ce8",marginTop:13}})
